language: c
install:
  - mkdir ~/devkitPro || true
  - pushd ~/devkitPro
  - export DEVKITPRO=$PWD
  - export DEVKITPPC=$PWD/devkitPPC
  - export DEVKITARM=$PWD/devkitARM
  - wget -N http://download.sourceforge.net/project/devkitpro/Automated%20Installer/devkitPPCupdate.pl
  - wget -N http://download.sourceforge.net/project/devkitpro/Automated%20Installer/devkitARMupdate.pl
  - chmod a+x devkit*update.pl
  - ./devkitPPCupdate.pl
  - ./devkitARMupdate.pl
  - popd
script:
  - ./Build.sh
  - cmp loader/loader.dol nintendont/boot.dol
cache:
  directories:
    - $HOME/devkitPro
before_deploy: zip -r9 nintendont.zip nintendont
